name: Stocker CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout
      uses: actions/checkout@master
    - name: Tests
      run: make test
    - name: Build
      run: make
    - name: Generate coverage
      run: make codecov
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        verbose: true
